# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antimw.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='antimw.proto',
  package='antimwpb',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61ntimw.proto\x12\x08\x61ntimwpb\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x0eThreatEventDto\x12\x11\n\teventType\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nthreatPath\x18\x03 \x01(\t\x12\x12\n\nthreatName\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_THREATEVENTDTO = _descriptor.Descriptor(
  name='ThreatEventDto',
  full_name='antimwpb.ThreatEventDto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventType', full_name='antimwpb.ThreatEventDto.eventType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='antimwpb.ThreatEventDto.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threatPath', full_name='antimwpb.ThreatEventDto.threatPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threatName', full_name='antimwpb.ThreatEventDto.threatName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=181,
)

_THREATEVENTDTO.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ThreatEventDto'] = _THREATEVENTDTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThreatEventDto = _reflection.GeneratedProtocolMessageType('ThreatEventDto', (_message.Message,), dict(
  DESCRIPTOR = _THREATEVENTDTO,
  __module__ = 'antimw_pb2'
  # @@protoc_insertion_point(class_scope:antimwpb.ThreatEventDto)
  ))
_sym_db.RegisterMessage(ThreatEventDto)


# @@protoc_insertion_point(module_scope)
